version: '3'

networks:
  web:
    external: true
  django-johanna:
    external: false

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: portfolio_johanna_production_django
    volumes:
      - production_django_media:/app/portfolio_johanna/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - web
      - django-johanna
    labels:
      - "traefik.http.routers.nginx-johanna.rule=Host(`johanna-zimmermann.com`)"
      - traefik.http.routers.django-johanna.tls=true
      - traefik.http.routers.django-johanna.tls.certresolver=le-resolver
      - traefik.http.services.django-johanna.loadbalancer.server.port=5000
      - traefik.http.middlewares.csrf.headers.hostsproxyheaders='X-CSRFToken'
      - traefik.http.routers.django-johanna.middlewares=csrf
      - traefik.http.routers.django-johanna.entrypoints=websecure

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: portfolio_johanna_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - django-johanna
    labels:
      - traefik.enable=false

  redis:
    image: redis:6
    networks:
      - django-johanna
    labels:
      - traefik.enable=false

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: portfolio_johanna_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    networks:
      - django-johanna
      - web
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx-johanna.loadbalancer.server.port=80
      - "traefik.http.routers.nginx-johanna.rule=Host(`johanna-zimmermann.com`) && PathPrefix(`/media/`)"
      - traefik.http.routers.nginx-johanna.tls=true
      - traefik.http.routers.nginx-johanna.tls.certresolver=le-resolver
      - traefik.http.routers.nginx-johanna.middlewares=csrf
      - traefik.http.routers.nginx-johanna.entrypoints=websecure

