# Generated by Django 4.2.9 on 2024-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="home/")),
                ("name", models.CharField(max_length=30)),
                ("job_role", models.CharField(max_length=30)),
            ],
        ),
    ]
