# Generated by Django 4.2.9 on 2024-02-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.ImageField(upload_to="home/")),
            ],
        ),
        migrations.AlterField(
            model_name="home",
            name="image",
            field=models.ImageField(upload_to="home/", verbose_name="Home bild"),
        ),
        migrations.AlterField(
            model_name="home",
            name="job_role",
            field=models.CharField(max_length=30, verbose_name="Dein Jobbezeichnung"),
        ),
        migrations.AlterField(
            model_name="home",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="HeaderLinks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                (
                    "data_hover",
                    models.CharField(
                        default="<django.db.models.fields.CharField>", max_length=50, verbose_name="Hovername"
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        default="#<django.db.models.fields.CharField>", max_length=50, verbose_name="Link"
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="portfolio.header"
                    ),
                ),
            ],
        ),
    ]
