# Generated by Django 4.2.9 on 2024-02-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_header_alter_home_image_alter_home_job_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headerlinks",
            name="header",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="links", to="portfolio.header"
            ),
        ),
    ]
