# Generated by Django 4.2.9 on 2024-02-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_alter_headerlinks_data_hover_alter_headerlinks_href"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=50, verbose_name="Adresse")),
                ("email", models.CharField(max_length=40, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Telefonnummer")),
            ],
        ),
        migrations.CreateModel(
            name="SocialIconsContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                ("class_name", models.CharField(max_length=30, verbose_name="Klassenname")),
                ("href", models.TextField(verbose_name="Link")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="icons", to="portfolio.contact"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=40, verbose_name="Form Titel")),
                ("button_text", models.CharField(max_length=30, verbose_name="Form Button")),
                ("name_type", models.CharField(max_length=30, verbose_name="Feld Typ")),
                ("name_name", models.CharField(max_length=30, verbose_name="Feld Name")),
                ("name_id", models.CharField(max_length=30, verbose_name="Feld Id")),
                ("name_placeholder", models.CharField(max_length=40, verbose_name="Feld Placeholder")),
                ("email_type", models.CharField(max_length=30, verbose_name="Feld Typ")),
                ("email_name", models.CharField(max_length=30, verbose_name="Feld Name")),
                ("email_fiel_id", models.CharField(max_length=30, verbose_name="Feld Id")),
                ("email_placeholder", models.CharField(max_length=40, verbose_name="Feld Placeholder")),
                ("message_name", models.CharField(max_length=30, verbose_name="Feld Name")),
                ("message_fiel_id", models.CharField(max_length=30, verbose_name="Feld Id")),
                ("message_placeholder", models.CharField(max_length=40, verbose_name="Feld Placeholder")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forms", to="portfolio.contact"
                    ),
                ),
            ],
        ),
    ]
