# Generated by Django 4.2.9 on 2024-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_contact_socialiconscontact_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="title",
            field=models.CharField(default="Konkaktieren Sie mich", max_length=30, verbose_name="Title"),
        ),
    ]
