# Generated by Django 4.2.9 on 2024-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_contact_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.ImageField(upload_to="footer/")),
                ("copy_right", models.CharField(max_length=30, verbose_name="Copyright")),
            ],
        ),
    ]
