# Generated by Django 4.2.9 on 2024-02-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(default="<django.db.models.fields.CharField>", verbose_name="Slug"),
        ),
    ]
