# Generated by Django 4.2.9 on 2024-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("header", models.CharField(max_length=40, verbose_name="Überschrift")),
                ("text", models.TextField(verbose_name="Text")),
            ],
        ),
    ]
