# Generated by Django 4.2.9 on 2024-06-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_textsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=50, verbose_name="Firmenname")),
                ("owner_name", models.CharField(max_length=60, verbose_name="Name der Geschäftsführerin")),
                ("street_name", models.CharField(max_length=100, verbose_name="Straße")),
                ("house_number", models.CharField(max_length=10, verbose_name="Hausnummer")),
                ("postel_code", models.CharField(max_length=6, verbose_name="Postleitzahl")),
                ("represented_by", models.CharField(max_length=60, verbose_name="Vertreten durch")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefonnummer")),
                ("email", models.CharField(max_length=30, verbose_name="E-Mail")),
            ],
        ),
    ]
