# Generated by Django 4.2.9 on 2024-06-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0011_imprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="imprint",
            name="city",
            field=models.CharField(default="Frankfurt", max_length=40, verbose_name="Stadt"),
        ),
    ]
