# Generated by Django 4.2.9 on 2024-06-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_imprint_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="imprint",
            name="tax_number",
            field=models.CharField(default=0, max_length=11, verbose_name="Steuernummer"),
        ),
    ]
