# Generated by Django 4.2.9 on 2025-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0014_portfolio_portfolioimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfTableAdjustedBodyPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40, verbose_name="Name")),
            ],
        ),
    ]
